version: "3.9"

services:
  webserver:
    image: nginx:latest
    container_name: webserver_docker
    restart: unless-stopped
    tty: true
    ports:
      - "1011:80"
    volumes:
      - ./src:/var/www/app
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    networks:
      - edugot_app

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-fpm
    container_name: php_docker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www/app
    volumes:
      - ./src:/var/www/app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - edugot_app

  db:
    image: mysql:latest
    container_name: mysql_docker
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: edugot_db
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - edugot_app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_docker
    links:
      - db
    restart: always
    ports:
       - "8080:80"
    networks:
      - edugot_app

networks:
  edugot_app:
    driver: bridge

volumes:
  dbdata:
    driver: local
